#!/bin/sh
# Generates the project's .cabal file.
# Must be run with the containing directory as the current directory.
stack build
stack exec gen-non-empty-sequence-cabal > ../non-empty-sequence/non-empty-sequence.cabal
